# Site settings
title: Tiempo de María
email: contacto@tiempodemaria.com.uy
#baseurl: "/tiempo-de-maria/"                    # the subpath of your site, e.g. /blog/
#url: "http://antonellaclavero.github.io"         # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: /:categories/:title

collections:
    oraciones:
        output: true
        permalink: /oraciones/:path/
    santorosario:
        output: true
        permalink: /santorosario/:path/
    misterios:
        output: true
        permalink: /santorosario/misterios/:path/
    jaculatorias:
        output: false